// Precompile the frontend: Babel-compile every .jsx offline and concatenate
// them into frontend/bundle.js in dependency order.
// The HTML then loads only vendor/react + bundle.js, with no babel at runtime.
// Runtime babel + fetch of external jsx fails under the Tauri asset protocol.
const fs = require("fs"), vm = require("vm"), path = require("path");
const FE = path.join(__dirname, "..", "src", "p2w_gui", "frontend");

// Load Babel standalone in its own sandbox.
const bs = {}; bs.self = bs; bs.window = bs; bs.globalThis = bs;
vm.createContext(bs);
vm.runInContext(fs.readFileSync(path.join(FE, "vendor", "babel.min.js"), "utf8"), bs);
const Babel = bs.Babel || bs.window.Babel;
if (!Babel) { console.error("Babel failed to load"); process.exit(1); }

// Same load order as the original <script type="text/babel"> tags.
const order = ["parts", "app"];
let out = "// AUTO-GENERATED by scripts/build_frontend.js -- do not edit\n\"use strict\";\n";
for (const name of order) {
  const src = fs.readFileSync(path.join(FE, name + ".jsx"), "utf8");
  const { code } = Babel.transform(src, { presets: ["react"], filename: name + ".jsx" });
  out += `\n/* ===== ${name}.jsx ===== */\n${code}\n`;
}
fs.writeFileSync(path.join(FE, "bundle.js"), out);
console.log(`✅ bundle.js written (${(out.length / 1024).toFixed(0)} KB, ${order.length} modules)`);
